sudo: required
dist: trusty
os:   linux
services:
    - docker
language: cpp
compiler:
    - gcc
before_install:
    - docker build --tag=dash/testing ./docker-testing
script:
    - docker run -d dash/testing -v .:/opt/dash /bin/sh -c "cd /opt/dash; sh dash/scripts/dash-ci.sh;"
after_failure:
    - cat ./build-ci/*/*/*.log
