sudo: required
dist: trusty
os:   linux
services:
    - docker
language: cpp
compiler:
    - gcc
before_install:
    - docker build --tag=dash/testing ./dash/scripts/docker-testing/
script:
    - docker run -v $PWD:/opt/dash dash/testing /bin/sh -c "export MPI_EXEC_FLAGS='--allow-run-as-root'; cd /opt/dash; sh dash/scripts/dash-ci.sh > /opt/dash/dash-ci.log 2> /opt/dash/dash-ci.err;"
    - cat ./dash-ci.log | grep "PASSED" || return 1
after_script:
    - cat ./dash-ci.log
    - cat ./dash-ci.err
    - cat ./build-ci/*/*/*.log
