version: 2
jobs:
  gnu_mpich:
    docker:
      - image: dashproject/ci:mpich
    environment:
      DASH_MAKE_PROCS: 2
      DASH_MAX_UNITS: 3
      DASH_BUILDEX: OFF
      CC: gcc
      CXX: g++
    steps:
      - checkout
      - run: bash dash/scripts/dash-ci.sh Release
      - run: bash dash/scripts/dash-ci.sh Minimal
      - run:
          command: bash dash/scripts/circleci/collect-artifacts.sh
          when: always
      - store_artifacts:
          path: /tmp/build-logs

  gnu_openmpi2:
    docker:
      - image: dashproject/ci:openmpi2
    environment:
      DASH_MAKE_PROCS: 2
      DASH_MAX_UNITS: 3
      DASH_BUILDEX: OFF
      CC: gcc
      CXX: g++
    steps:
      - checkout
      - run: bash dash/scripts/dash-ci.sh Release
      - run: bash dash/scripts/dash-ci.sh Minimal
      - run:
          command: bash dash/scripts/circleci/collect-artifacts.sh
          when: always
      - store_artifacts:
          path: /tmp/build-logs

  clang_mpich:
    docker:
      - image: dashproject/ci:mpich
    environment:
      DASH_MAKE_PROCS: 2
      DASH_MAX_UNITS: 3
      DASH_BUILDEX: OFF
      CC: clang-3.8
      CXX: clang++-3.8
    steps:
      - checkout
      - run: bash dash/scripts/dash-ci.sh Release
      - run: bash dash/scripts/dash-ci.sh Minimal
      - run:
          command: bash dash/scripts/circleci/collect-artifacts.sh
          when: always
      - store_artifacts:
          path: /tmp/build-logs


workflows:
  version: 2
  build_and_test:
    jobs:
      - gnu_mpich
      - gnu_openmpi2
      - clang_mpich

